### ISSUE TITLE
ball is changing position on touch 

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [simonnorberg/fling-animation-demo#2]
When i click anywhere the ball is changing its location to that position without flick .how to prevent that?

**Comment by simonnorberg** [comment]
I think you can compare the MotionEvent coordinates in [`onActionDown()`](https://github.com/simonnorberg/fling-animation-demo/blob/master/app/src/main/java/net/simno/flinganimationdemo/CircleView.kt#L123) with `circleX` and `circleY` and then decide if you want to call `updatePosition(event.x, event.y)` to change the circle position on the screen.
